/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ArtifactsCodeRouteImport } from './routes/artifacts.$code'
import { Route as AuthenticatedScanRouteImport } from './routes/_authenticated/scan'
import { Route as AuthenticatedRewardsRouteImport } from './routes/_authenticated/rewards'
import { Route as AuthenticatedQuizzesRouteImport } from './routes/_authenticated/quizzes'
import { Route as AuthenticatedQuestsRouteImport } from './routes/_authenticated/quests'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedMapRouteImport } from './routes/_authenticated/map'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedJourneyRouteImport } from './routes/_authenticated/journey'
import { Route as AuthenticatedJournalRouteImport } from './routes/_authenticated/journal'
import { Route as AuthenticatedFriendsRouteImport } from './routes/_authenticated/friends'
import { Route as AuthenticatedAchievementsRouteImport } from './routes/_authenticated/achievements'
import { Route as AdminArtifactsIndexRouteImport } from './routes/admin/artifacts/index'
import { Route as AdminArtifactsNewRouteImport } from './routes/admin/artifacts/new'
import { Route as AdminArtifactsIdRouteImport } from './routes/admin/artifacts/$id'
import { Route as AuthenticatedProfileUserIdRouteImport } from './routes/_authenticated/profile.$userId'
import { Route as AuthenticatedArtifactIdRouteImport } from './routes/_authenticated/artifact.$id'
import { Route as AdminArtifactsQuizzesIdRouteImport } from './routes/admin/artifacts/quizzes.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ArtifactsCodeRoute = ArtifactsCodeRouteImport.update({
  id: '/artifacts/$code',
  path: '/artifacts/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedScanRoute = AuthenticatedScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRewardsRoute = AuthenticatedRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuizzesRoute = AuthenticatedQuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuestsRoute = AuthenticatedQuestsRouteImport.update({
  id: '/quests',
  path: '/quests',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMapRoute = AuthenticatedMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJourneyRoute = AuthenticatedJourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJournalRoute = AuthenticatedJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFriendsRoute = AuthenticatedFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAchievementsRoute =
  AuthenticatedAchievementsRouteImport.update({
    id: '/achievements',
    path: '/achievements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AdminArtifactsIndexRoute = AdminArtifactsIndexRouteImport.update({
  id: '/artifacts/',
  path: '/artifacts/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminArtifactsNewRoute = AdminArtifactsNewRouteImport.update({
  id: '/artifacts/new',
  path: '/artifacts/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminArtifactsIdRoute = AdminArtifactsIdRouteImport.update({
  id: '/artifacts/$id',
  path: '/artifacts/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthenticatedProfileUserIdRoute =
  AuthenticatedProfileUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedArtifactIdRoute = AuthenticatedArtifactIdRouteImport.update({
  id: '/artifact/$id',
  path: '/artifact/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdminArtifactsQuizzesIdRoute = AdminArtifactsQuizzesIdRouteImport.update({
  id: '/artifacts/quizzes/$id',
  path: '/artifacts/quizzes/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/friends': typeof AuthenticatedFriendsRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/journey': typeof AuthenticatedJourneyRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/map': typeof AuthenticatedMapRoute
  '/profile': typeof AuthenticatedProfileRouteWithChildren
  '/quests': typeof AuthenticatedQuestsRoute
  '/quizzes': typeof AuthenticatedQuizzesRoute
  '/rewards': typeof AuthenticatedRewardsRoute
  '/scan': typeof AuthenticatedScanRoute
  '/artifacts/$code': typeof ArtifactsCodeRoute
  '/admin/': typeof AdminIndexRoute
  '/artifact/$id': typeof AuthenticatedArtifactIdRoute
  '/profile/$userId': typeof AuthenticatedProfileUserIdRoute
  '/admin/artifacts/$id': typeof AdminArtifactsIdRoute
  '/admin/artifacts/new': typeof AdminArtifactsNewRoute
  '/admin/artifacts/': typeof AdminArtifactsIndexRoute
  '/admin/artifacts/quizzes/$id': typeof AdminArtifactsQuizzesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/friends': typeof AuthenticatedFriendsRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/journey': typeof AuthenticatedJourneyRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/map': typeof AuthenticatedMapRoute
  '/profile': typeof AuthenticatedProfileRouteWithChildren
  '/quests': typeof AuthenticatedQuestsRoute
  '/quizzes': typeof AuthenticatedQuizzesRoute
  '/rewards': typeof AuthenticatedRewardsRoute
  '/scan': typeof AuthenticatedScanRoute
  '/artifacts/$code': typeof ArtifactsCodeRoute
  '/admin': typeof AdminIndexRoute
  '/artifact/$id': typeof AuthenticatedArtifactIdRoute
  '/profile/$userId': typeof AuthenticatedProfileUserIdRoute
  '/admin/artifacts/$id': typeof AdminArtifactsIdRoute
  '/admin/artifacts/new': typeof AdminArtifactsNewRoute
  '/admin/artifacts': typeof AdminArtifactsIndexRoute
  '/admin/artifacts/quizzes/$id': typeof AdminArtifactsQuizzesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/achievements': typeof AuthenticatedAchievementsRoute
  '/_authenticated/friends': typeof AuthenticatedFriendsRoute
  '/_authenticated/journal': typeof AuthenticatedJournalRoute
  '/_authenticated/journey': typeof AuthenticatedJourneyRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/map': typeof AuthenticatedMapRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRouteWithChildren
  '/_authenticated/quests': typeof AuthenticatedQuestsRoute
  '/_authenticated/quizzes': typeof AuthenticatedQuizzesRoute
  '/_authenticated/rewards': typeof AuthenticatedRewardsRoute
  '/_authenticated/scan': typeof AuthenticatedScanRoute
  '/artifacts/$code': typeof ArtifactsCodeRoute
  '/admin/': typeof AdminIndexRoute
  '/_authenticated/artifact/$id': typeof AuthenticatedArtifactIdRoute
  '/_authenticated/profile/$userId': typeof AuthenticatedProfileUserIdRoute
  '/admin/artifacts/$id': typeof AdminArtifactsIdRoute
  '/admin/artifacts/new': typeof AdminArtifactsNewRoute
  '/admin/artifacts/': typeof AdminArtifactsIndexRoute
  '/admin/artifacts/quizzes/$id': typeof AdminArtifactsQuizzesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/achievements'
    | '/friends'
    | '/journal'
    | '/journey'
    | '/leaderboard'
    | '/map'
    | '/profile'
    | '/quests'
    | '/quizzes'
    | '/rewards'
    | '/scan'
    | '/artifacts/$code'
    | '/admin/'
    | '/artifact/$id'
    | '/profile/$userId'
    | '/admin/artifacts/$id'
    | '/admin/artifacts/new'
    | '/admin/artifacts/'
    | '/admin/artifacts/quizzes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/achievements'
    | '/friends'
    | '/journal'
    | '/journey'
    | '/leaderboard'
    | '/map'
    | '/profile'
    | '/quests'
    | '/quizzes'
    | '/rewards'
    | '/scan'
    | '/artifacts/$code'
    | '/admin'
    | '/artifact/$id'
    | '/profile/$userId'
    | '/admin/artifacts/$id'
    | '/admin/artifacts/new'
    | '/admin/artifacts'
    | '/admin/artifacts/quizzes/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/auth'
    | '/_authenticated/achievements'
    | '/_authenticated/friends'
    | '/_authenticated/journal'
    | '/_authenticated/journey'
    | '/_authenticated/leaderboard'
    | '/_authenticated/map'
    | '/_authenticated/profile'
    | '/_authenticated/quests'
    | '/_authenticated/quizzes'
    | '/_authenticated/rewards'
    | '/_authenticated/scan'
    | '/artifacts/$code'
    | '/admin/'
    | '/_authenticated/artifact/$id'
    | '/_authenticated/profile/$userId'
    | '/admin/artifacts/$id'
    | '/admin/artifacts/new'
    | '/admin/artifacts/'
    | '/admin/artifacts/quizzes/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ArtifactsCodeRoute: typeof ArtifactsCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/artifacts/$code': {
      id: '/artifacts/$code'
      path: '/artifacts/$code'
      fullPath: '/artifacts/$code'
      preLoaderRoute: typeof ArtifactsCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/scan': {
      id: '/_authenticated/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof AuthenticatedScanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rewards': {
      id: '/_authenticated/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof AuthenticatedRewardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quizzes': {
      id: '/_authenticated/quizzes'
      path: '/quizzes'
      fullPath: '/quizzes'
      preLoaderRoute: typeof AuthenticatedQuizzesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quests': {
      id: '/_authenticated/quests'
      path: '/quests'
      fullPath: '/quests'
      preLoaderRoute: typeof AuthenticatedQuestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/map': {
      id: '/_authenticated/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AuthenticatedMapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/journey': {
      id: '/_authenticated/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof AuthenticatedJourneyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/journal': {
      id: '/_authenticated/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AuthenticatedJournalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/friends': {
      id: '/_authenticated/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof AuthenticatedFriendsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/achievements': {
      id: '/_authenticated/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AuthenticatedAchievementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/artifacts/': {
      id: '/admin/artifacts/'
      path: '/artifacts'
      fullPath: '/admin/artifacts/'
      preLoaderRoute: typeof AdminArtifactsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/artifacts/new': {
      id: '/admin/artifacts/new'
      path: '/artifacts/new'
      fullPath: '/admin/artifacts/new'
      preLoaderRoute: typeof AdminArtifactsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/artifacts/$id': {
      id: '/admin/artifacts/$id'
      path: '/artifacts/$id'
      fullPath: '/admin/artifacts/$id'
      preLoaderRoute: typeof AdminArtifactsIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authenticated/profile/$userId': {
      id: '/_authenticated/profile/$userId'
      path: '/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof AuthenticatedProfileUserIdRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/artifact/$id': {
      id: '/_authenticated/artifact/$id'
      path: '/artifact/$id'
      fullPath: '/artifact/$id'
      preLoaderRoute: typeof AuthenticatedArtifactIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/artifacts/quizzes/$id': {
      id: '/admin/artifacts/quizzes/$id'
      path: '/artifacts/quizzes/$id'
      fullPath: '/admin/artifacts/quizzes/$id'
      preLoaderRoute: typeof AdminArtifactsQuizzesIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AuthenticatedProfileRouteChildren {
  AuthenticatedProfileUserIdRoute: typeof AuthenticatedProfileUserIdRoute
}

const AuthenticatedProfileRouteChildren: AuthenticatedProfileRouteChildren = {
  AuthenticatedProfileUserIdRoute: AuthenticatedProfileUserIdRoute,
}

const AuthenticatedProfileRouteWithChildren =
  AuthenticatedProfileRoute._addFileChildren(AuthenticatedProfileRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAchievementsRoute: typeof AuthenticatedAchievementsRoute
  AuthenticatedFriendsRoute: typeof AuthenticatedFriendsRoute
  AuthenticatedJournalRoute: typeof AuthenticatedJournalRoute
  AuthenticatedJourneyRoute: typeof AuthenticatedJourneyRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedMapRoute: typeof AuthenticatedMapRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRouteWithChildren
  AuthenticatedQuestsRoute: typeof AuthenticatedQuestsRoute
  AuthenticatedQuizzesRoute: typeof AuthenticatedQuizzesRoute
  AuthenticatedRewardsRoute: typeof AuthenticatedRewardsRoute
  AuthenticatedScanRoute: typeof AuthenticatedScanRoute
  AuthenticatedArtifactIdRoute: typeof AuthenticatedArtifactIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAchievementsRoute: AuthenticatedAchievementsRoute,
  AuthenticatedFriendsRoute: AuthenticatedFriendsRoute,
  AuthenticatedJournalRoute: AuthenticatedJournalRoute,
  AuthenticatedJourneyRoute: AuthenticatedJourneyRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedMapRoute: AuthenticatedMapRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRouteWithChildren,
  AuthenticatedQuestsRoute: AuthenticatedQuestsRoute,
  AuthenticatedQuizzesRoute: AuthenticatedQuizzesRoute,
  AuthenticatedRewardsRoute: AuthenticatedRewardsRoute,
  AuthenticatedScanRoute: AuthenticatedScanRoute,
  AuthenticatedArtifactIdRoute: AuthenticatedArtifactIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminArtifactsIdRoute: typeof AdminArtifactsIdRoute
  AdminArtifactsNewRoute: typeof AdminArtifactsNewRoute
  AdminArtifactsIndexRoute: typeof AdminArtifactsIndexRoute
  AdminArtifactsQuizzesIdRoute: typeof AdminArtifactsQuizzesIdRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminArtifactsIdRoute: AdminArtifactsIdRoute,
  AdminArtifactsNewRoute: AdminArtifactsNewRoute,
  AdminArtifactsIndexRoute: AdminArtifactsIndexRoute,
  AdminArtifactsQuizzesIdRoute: AdminArtifactsQuizzesIdRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ArtifactsCodeRoute: ArtifactsCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
